; Auto-generated. Do not edit!


(cl:in-package learning_communication-msg)


;//! \htmlinclude DoDishesGoal.msg.html

(cl:defclass <DoDishesGoal> (roslisp-msg-protocol:ros-message)
  ((diswasher_id
    :reader diswasher_id
    :initarg :diswasher_id
    :type cl:integer
    :initform 0))
)

(cl:defclass DoDishesGoal (<DoDishesGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <DoDishesGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'DoDishesGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name learning_communication-msg:<DoDishesGoal> is deprecated: use learning_communication-msg:DoDishesGoal instead.")))

(cl:ensure-generic-function 'diswasher_id-val :lambda-list '(m))
(cl:defmethod diswasher_id-val ((m <DoDishesGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader learning_communication-msg:diswasher_id-val is deprecated.  Use learning_communication-msg:diswasher_id instead.")
  (diswasher_id m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <DoDishesGoal>) ostream)
  "Serializes a message object of type '<DoDishesGoal>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'diswasher_id)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'diswasher_id)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'diswasher_id)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'diswasher_id)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <DoDishesGoal>) istream)
  "Deserializes a message object of type '<DoDishesGoal>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'diswasher_id)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'diswasher_id)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'diswasher_id)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'diswasher_id)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<DoDishesGoal>)))
  "Returns string type for a message object of type '<DoDishesGoal>"
  "learning_communication/DoDishesGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'DoDishesGoal)))
  "Returns string type for a message object of type 'DoDishesGoal"
  "learning_communication/DoDishesGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<DoDishesGoal>)))
  "Returns md5sum for a message object of type '<DoDishesGoal>"
  "467f445409e7b1f0897082d573f0e4ed")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'DoDishesGoal)))
  "Returns md5sum for a message object of type 'DoDishesGoal"
  "467f445409e7b1f0897082d573f0e4ed")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<DoDishesGoal>)))
  "Returns full string definition for message of type '<DoDishesGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%uint32 diswasher_id~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'DoDishesGoal)))
  "Returns full string definition for message of type 'DoDishesGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%uint32 diswasher_id~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <DoDishesGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <DoDishesGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'DoDishesGoal
    (cl:cons ':diswasher_id (diswasher_id msg))
))
