; Auto-generated. Do not edit!


(cl:in-package learning_communication-msg)


;//! \htmlinclude DoDisherGoal.msg.html

(cl:defclass <DoDisherGoal> (roslisp-msg-protocol:ros-message)
  ((diswasher_id
    :reader diswasher_id
    :initarg :diswasher_id
    :type cl:integer
    :initform 0))
)

(cl:defclass DoDisherGoal (<DoDisherGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <DoDisherGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'DoDisherGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name learning_communication-msg:<DoDisherGoal> is deprecated: use learning_communication-msg:DoDisherGoal instead.")))

(cl:ensure-generic-function 'diswasher_id-val :lambda-list '(m))
(cl:defmethod diswasher_id-val ((m <DoDisherGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader learning_communication-msg:diswasher_id-val is deprecated.  Use learning_communication-msg:diswasher_id instead.")
  (diswasher_id m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <DoDisherGoal>) ostream)
  "Serializes a message object of type '<DoDisherGoal>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'diswasher_id)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'diswasher_id)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'diswasher_id)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'diswasher_id)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <DoDisherGoal>) istream)
  "Deserializes a message object of type '<DoDisherGoal>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'diswasher_id)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'diswasher_id)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'diswasher_id)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'diswasher_id)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<DoDisherGoal>)))
  "Returns string type for a message object of type '<DoDisherGoal>"
  "learning_communication/DoDisherGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'DoDisherGoal)))
  "Returns string type for a message object of type 'DoDisherGoal"
  "learning_communication/DoDisherGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<DoDisherGoal>)))
  "Returns md5sum for a message object of type '<DoDisherGoal>"
  "467f445409e7b1f0897082d573f0e4ed")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'DoDisherGoal)))
  "Returns md5sum for a message object of type 'DoDisherGoal"
  "467f445409e7b1f0897082d573f0e4ed")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<DoDisherGoal>)))
  "Returns full string definition for message of type '<DoDisherGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%uint32 diswasher_id~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'DoDisherGoal)))
  "Returns full string definition for message of type 'DoDisherGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%uint32 diswasher_id~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <DoDisherGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <DoDisherGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'DoDisherGoal
    (cl:cons ':diswasher_id (diswasher_id msg))
))
