// Generated by gencpp from file learning_communication/AddTwolntsRequest.msg
// DO NOT EDIT!


#ifndef LEARNING_COMMUNICATION_MESSAGE_ADDTWOLNTSREQUEST_H
#define LEARNING_COMMUNICATION_MESSAGE_ADDTWOLNTSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace learning_communication
{
template <class ContainerAllocator>
struct AddTwolntsRequest_
{
  typedef AddTwolntsRequest_<ContainerAllocator> Type;

  AddTwolntsRequest_()
    : a(0)
    , b(0)  {
    }
  AddTwolntsRequest_(const ContainerAllocator& _alloc)
    : a(0)
    , b(0)  {
  (void)_alloc;
    }



   typedef int64_t _a_type;
  _a_type a;

   typedef int64_t _b_type;
  _b_type b;





  typedef boost::shared_ptr< ::learning_communication::AddTwolntsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::learning_communication::AddTwolntsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AddTwolntsRequest_

typedef ::learning_communication::AddTwolntsRequest_<std::allocator<void> > AddTwolntsRequest;

typedef boost::shared_ptr< ::learning_communication::AddTwolntsRequest > AddTwolntsRequestPtr;
typedef boost::shared_ptr< ::learning_communication::AddTwolntsRequest const> AddTwolntsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::learning_communication::AddTwolntsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::learning_communication::AddTwolntsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::learning_communication::AddTwolntsRequest_<ContainerAllocator1> & lhs, const ::learning_communication::AddTwolntsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a &&
    lhs.b == rhs.b;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::learning_communication::AddTwolntsRequest_<ContainerAllocator1> & lhs, const ::learning_communication::AddTwolntsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace learning_communication

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::learning_communication::AddTwolntsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::learning_communication::AddTwolntsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::learning_communication::AddTwolntsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::learning_communication::AddTwolntsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::learning_communication::AddTwolntsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::learning_communication::AddTwolntsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::learning_communication::AddTwolntsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "36d09b846be0b371c5f190354dd3153e";
  }

  static const char* value(const ::learning_communication::AddTwolntsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x36d09b846be0b371ULL;
  static const uint64_t static_value2 = 0xc5f190354dd3153eULL;
};

template<class ContainerAllocator>
struct DataType< ::learning_communication::AddTwolntsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "learning_communication/AddTwolntsRequest";
  }

  static const char* value(const ::learning_communication::AddTwolntsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::learning_communication::AddTwolntsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 a \n"
"int64 b\n"
;
  }

  static const char* value(const ::learning_communication::AddTwolntsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::learning_communication::AddTwolntsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddTwolntsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::learning_communication::AddTwolntsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::learning_communication::AddTwolntsRequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<int64_t>::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    Printer<int64_t>::stream(s, indent + "  ", v.b);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LEARNING_COMMUNICATION_MESSAGE_ADDTWOLNTSREQUEST_H
