// Generated by gencpp from file learning_communication/AddTwolnts.msg
// DO NOT EDIT!


#ifndef LEARNING_COMMUNICATION_MESSAGE_ADDTWOLNTS_H
#define LEARNING_COMMUNICATION_MESSAGE_ADDTWOLNTS_H

#include <ros/service_traits.h>


#include <learning_communication/AddTwolntsRequest.h>
#include <learning_communication/AddTwolntsResponse.h>


namespace learning_communication
{

struct AddTwolnts
{

typedef AddTwolntsRequest Request;
typedef AddTwolntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwolnts
} // namespace learning_communication


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::learning_communication::AddTwolnts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::learning_communication::AddTwolnts&) { return value(); }
};

template<>
struct DataType< ::learning_communication::AddTwolnts > {
  static const char* value()
  {
    return "learning_communication/AddTwolnts";
  }

  static const char* value(const ::learning_communication::AddTwolnts&) { return value(); }
};


// service_traits::MD5Sum< ::learning_communication::AddTwolntsRequest> should match
// service_traits::MD5Sum< ::learning_communication::AddTwolnts >
template<>
struct MD5Sum< ::learning_communication::AddTwolntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::learning_communication::AddTwolnts >::value();
  }
  static const char* value(const ::learning_communication::AddTwolntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::learning_communication::AddTwolntsRequest> should match
// service_traits::DataType< ::learning_communication::AddTwolnts >
template<>
struct DataType< ::learning_communication::AddTwolntsRequest>
{
  static const char* value()
  {
    return DataType< ::learning_communication::AddTwolnts >::value();
  }
  static const char* value(const ::learning_communication::AddTwolntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::learning_communication::AddTwolntsResponse> should match
// service_traits::MD5Sum< ::learning_communication::AddTwolnts >
template<>
struct MD5Sum< ::learning_communication::AddTwolntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::learning_communication::AddTwolnts >::value();
  }
  static const char* value(const ::learning_communication::AddTwolntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::learning_communication::AddTwolntsResponse> should match
// service_traits::DataType< ::learning_communication::AddTwolnts >
template<>
struct DataType< ::learning_communication::AddTwolntsResponse>
{
  static const char* value()
  {
    return DataType< ::learning_communication::AddTwolnts >::value();
  }
  static const char* value(const ::learning_communication::AddTwolntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LEARNING_COMMUNICATION_MESSAGE_ADDTWOLNTS_H
