// Auto-generated. Do not edit!

// (in-package learning_communication.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class DoDishesGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.diswasher_id = null;
    }
    else {
      if (initObj.hasOwnProperty('diswasher_id')) {
        this.diswasher_id = initObj.diswasher_id
      }
      else {
        this.diswasher_id = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type DoDishesGoal
    // Serialize message field [diswasher_id]
    bufferOffset = _serializer.uint32(obj.diswasher_id, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type DoDishesGoal
    let len;
    let data = new DoDishesGoal(null);
    // Deserialize message field [diswasher_id]
    data.diswasher_id = _deserializer.uint32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'learning_communication/DoDishesGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '467f445409e7b1f0897082d573f0e4ed';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    uint32 diswasher_id
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new DoDishesGoal(null);
    if (msg.diswasher_id !== undefined) {
      resolved.diswasher_id = msg.diswasher_id;
    }
    else {
      resolved.diswasher_id = 0
    }

    return resolved;
    }
};

module.exports = DoDishesGoal;
